spring:
  datasource:
    url: jdbc:mysql://localhost:3306/console?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.groovy

ssh:
  shell:
    user: admin
    password: password
    port: 10022
